l_english:
 edict_scm_set_the_hab_settings:0 "§BSCM Session Settings§!"
 edict_scm_set_the_hab_settings_desc:0 "Set various game settings. such as habitat cap, fallen empire and crisis strength."

 scm_owned_habitat_count:0 "Owned habitat count"
 scm_habitat_softcap:0 "Habitat Softcap"
 scm_habitat_hardcap:0 "Habitat Hardcap"
 scm_over_habitat_cap:0 "§RHabitat hardcap reached§!"

 decision_scm_abandon_overcap_habitat:0 "Abandon Habitat"
 decision_scm_abandon_overcap_habitat_desc:0 "Your nation is over the habitat softcap. To avoid habitat debuffs you can abandon habitats for free until you are under the habitat softcap. All buildings/pops/districts/resources invested into the habitat are made void and the colony on it will be destroyed."

 scm_habitat_limit_bonk_1:0 "Over habitat limit 1"
 scm_habitat_limit_bonk_1_desc:0 "Limited debuffs for being naughty.\nYou are allowed to abandon habitats for free until you are under the softcap again.\nThe habitat softcap is §B[owner.scm_habitat_softcap]§!."
 scm_habitat_limit_bonk_2:0 "Over habitat limit 2"
 scm_habitat_limit_bonk_2_desc:0 "Limited debuffs for being naughty.\nYou are allowed to abandon habitats for free until you are under the softcap again.\nThe habitat softcap is §B[owner.scm_habitat_softcap]§!."
 scm_habitat_limit_bonk_3:0 "Over habitat limit 3"
 scm_habitat_limit_bonk_3_desc:0 "Bigger debuffs for being naughty.\nYou are allowed to abandon habitats for free until you are under the softcap again.\nThe habitat softcap is §B[owner.scm_habitat_softcap]§!."
 scm_habitat_limit_bonk_4:0 "Over habitat limit 4"
 scm_habitat_limit_bonk_4_desc:0 "Big Chungus debuffs for being naughty.\nYou are allowed to abandon habitats for free until you are under the softcap again.\nThe habitat softcap is §B[owner.scm_habitat_softcap]§!."
 scm_habitat_limit_bonk_5:0 "Over habitat limit 5"
 scm_habitat_limit_bonk_5_desc:0 "Massive debuffs for being naughty.\nYou are allowed to abandon habitats for free until you are under the softcap again.\nThe habitat softcap is §B[owner.scm_habitat_softcap]§!."
 scm_habitat_limit_bonk_6:0 "Over habitat limit 6"
 scm_habitat_limit_bonk_6_desc:0 "Why are you still going higher?.\nYou are allowed to abandon habitats for free until you are under the softcap again.\nThe habitat softcap is §B[owner.scm_habitat_softcap]§!."
 scm_habitat_limit_bonk_7:0 "Over habitat limit 7"
 scm_habitat_limit_bonk_7_desc:0 "Listen buddy, you are definitely doing something bad here.\nYou are allowed to abandon habitats for free until you are under the softcap again.\nThe habitat softcap is §B[owner.scm_habitat_softcap]§!."
 scm_habitat_limit_bonk_8:0 "Over habitat limit 8"
 scm_habitat_limit_bonk_8_desc:0 "Really? You're still going?.\nYou are allowed to abandon habitats for free until you are under the softcap again.\nThe habitat softcap is §B[owner.scm_habitat_softcap]§!."
 scm_habitat_limit_bonk_9:0 "Over habitat limit 9"
 scm_habitat_limit_bonk_9_desc:0 "Not cool, bruh.\nYou are allowed to abandon habitats for free until you are under the softcap again.\nThe habitat softcap is §B[owner.scm_habitat_softcap]§!."
 scm_habitat_limit_bonk_10:0 "Over habitat limit 10+"
 scm_habitat_limit_bonk_10_desc:0 "I don't know how you got here, but I hate you.\nYou are allowed to abandon habitats for free until you are under the softcap again.\nThe habitat softcap is §B[owner.scm_habitat_softcap]§!."

 scm_habitat_settings.1.title:0 "Set Habitat Softcap"
 scm_habitat_settings.1.desc:0 "The current §YSOFTCAP§! for habitats is §B[FROM.scm_habitat_softcap]§!.\nGoing over the §YSOFTCAP§! will impose increasingly harsher habitat §RDEBUFFS§!, while reaching the §YHARDCAP§! stops you from building any more habitats.\nOnly counts §YCOLONIZED§! habitats."
 scm_habitat_settings.1.a:0 "Decrease softcap by §R10§!"
 scm_habitat_settings.1.b:0 "Decrease softcap by §R5§!"
 scm_habitat_settings.1.c:0 "Decrease softcap by §R2§!"
 scm_habitat_settings.1.d:0 "Decrease softcap by §R1§!"
 scm_habitat_settings.1.e:0 "Increase softcap by §G1§!"
 scm_habitat_settings.1.f:0 "Increase softcap by §G2§!"
 scm_habitat_settings.1.g:0 "Increase softcap by §G5§!"
 scm_habitat_settings.1.h:0 "Increase softcap by §G10§!"
 scm_habitat_settings.1.i:0 "§RFinalize§! §YSOFTCAP§! selection. Go to §YHARDCAP§! selection."

 scm_habitat_settings.2.title:0 "Set Habitat §YHARDCAP§!"
 scm_habitat_settings.2.desc:0 "The current §YHARDCAP§! for habitats is §B[FROM.scm_habitat_hardcap]§!."
 scm_habitat_settings.2.a:0 "Decrease hardcap by §R10§!"
 scm_habitat_settings.2.b:0 "Decrease hardcap by §R5§!"
 scm_habitat_settings.2.c:0 "Decrease hardcap by §R2§!"
 scm_habitat_settings.2.d:0 "Decrease hardcap by §R1§!"
 scm_habitat_settings.2.e:0 "Increase hardcap by §G1§!"
 scm_habitat_settings.2.f:0 "Increase hardcap by §G2§!"
 scm_habitat_settings.2.g:0 "Increase hardcap by §G5§!"
 scm_habitat_settings.2.h:0 "Increase hardcap by §G10§!"
 scm_habitat_settings.2.i:0 "§RFinalize§! §YHARDCAP§! selection. Go to Void Dweller §GEXTRA§! cap selection."

 scm_habitat_settings.3.title:0 "Set §GEXTRA§! habitat cap for Void Dwellers"
 scm_habitat_settings.3.desc:0 "The current §GEXTRA§! cap for Void Dwellers is §B[FROM.scm_void_dwellers_extra_hab_count]§!. These settings apply both to §YHARDCAP§! and §YSOFTCAP§!."
 scm_habitat_settings.3.a:0 "Decrease extra cap by §R10§!"
 scm_habitat_settings.3.b:0 "Decrease extra cap by §R5§!"
 scm_habitat_settings.3.c:0 "Decrease extra cap by §R2§!"
 scm_habitat_settings.3.d:0 "Decrease extra cap by §R1§!"
 scm_habitat_settings.3.e:0 "Increase extra cap by §G1§!"
 scm_habitat_settings.3.f:0 "Increase extra cap by §G2§!"
 scm_habitat_settings.3.g:0 "Increase extra cap by §G5§!"
 scm_habitat_settings.3.h:0 "Increase extra cap by §G10§!"
 scm_habitat_settings.3.i:0 "§RFinalize§! habitat cap settings."

 scm_game_settings.1.title:0 "SCM Game Settings"
 scm_game_settings.1.desc:0 "Welcome to the SCM Game Settings section, here you can edit Habitat Settings, Fallen Empires, the Khan and force spawn a Crisis. Start by confirming that you are the host, so that the SCM Game Settings edict wouldn't bother other campaign players and stop them from accidentally changing settings."
 scm_game_settings.1.a:0 "§HBecome the Host§!"
 scm_game_settings.1.b:0 "Open Habitat Settings"
 scm_game_settings.1.c:0 "Open Fallen Empire Settings"
 scm_game_settings.1.d:0 "Open Khan Settings"
 scm_game_settings.1.e:0 "Open Force Spawn Settings"
 scm_game_settings.1.f:0 "One-Time Fleet Spawning Menu"
 scm_game_settings.1.g:0 "Misc Settings"
 scm_game_settings.1.z:0 "§RExit Settings Menu§!"
 
 scm_game_settings.1000.title:0 "Fallen Empire Settings"
 scm_game_settings.1000.desc:0 "Current Variables for Fallen Empires:\n§HExtra Hull§! - §G[FROM.scm_fe_hull_variable]%§!\n§YExtra Armor§! - §G[FROM.scm_fe_armor_variable]%§\n\n§BExtra Shields§! - §G[FROM.scm_fe_shield_variable]%§\n\n§RExtra Firing Rate§! - §G[FROM.scm_fe_firerate_variable]%§\n\n§GExtra Production from Jobs§! - §G[FROM.scm_fe_jobproduction_variable]%§\n\n§EExtra Ship Speed§! - §G[FROM.scm_fe_speed_variable]%§"\nBonus Fleets - §G[FROM.scm_fe_extrafleet_variable]§"

 scm_game_settings.1000.a:0 "Increase Ship Hull by §G10%§!"
 scm_game_settings.1000.b:0 "Decrease Ship Hull by §R10%§!"
 scm_game_settings.1000.c:0 "Increase Armor by §G10%§!"
 scm_game_settings.1000.d:0 "Decrease Armor by §R10%§!"
 scm_game_settings.1000.e:0 "Increase Shields by §G10%§!"
 scm_game_settings.1000.f:0 "Decrease Shields by §R10%§!"
 scm_game_settings.1000.g:0 "Increase Fire Rate by §G10%§!"
 scm_game_settings.1000.h:0 "Decrease Fire Rate by §R10%§!"
 scm_game_settings.1000.i:0 "Increase Job Production by §G10%§!"
 scm_game_settings.1000.j:0 "Decrease Job Production by §R10%§!"
 scm_game_settings.1000.k:0 "Increase Ship Speed by §G10%§!"
 scm_game_settings.1000.l:0 "Decrease Ship Speed by §R10%§!"
 scm_game_settings.1000.m:0 "Increase Extra Fleets by §G1§!"
 scm_game_settings.1000.n:0 "Decrease Extra Fleets by §R1§!"
 scm_game_settings.1000.z:0 "Finalize Variables, Pick Target"
 scm_game_settings.1000.z1:0 "Back to Main Settings Menu"

 scm_game_settings.1001.title:0 "Fallen Empire Target"
 scm_game_settings.1001.desc:0 "The Current Target is §Y[scm_fe_var_settings_target.GetName]§!"
 scm_game_settings.1001.a:0 "Change Target"
 scm_game_settings.1001.b:0 "Grant §Y[scm_fe_var_settings_target.GetName]§! the Bonuses"
 scm_game_settings.1001.c:0 "Grant §YEvery§! Fallen Empire the Bonuses"

 scm_fe_hull_variable_mod:0 "Ancient Hull Technologies"
 scm_fe_armor_variable_mod:0 "Ancient Armor Technologies"
 scm_fe_shield_variable_mod:0 "Ancient Shield Technologies"
 scm_fe_firerate_variable_mod:0 "Ancient Firing System Technologies"
 scm_fe_jobproduction_variable_mod:0 "Ancient Production Technologies"
 scm_fe_speed_variable_mod:0 "Ancient Propulsion Technologies"

 scm_game_settings.2000.title:0 "Khan Settings"
 scm_game_settings.2000.desc:0 "Current Variables for the Khan:\n§HExtra Hull§! - §G[FROM.scm_fe_hull_variable]%§!\n§YExtra Armor§! - §G[FROM.scm_fe_armor_variable]%§\n\n§BExtra Shields§! - §G[FROM.scm_fe_shield_variable]%§\n\n§RExtra Firing Rate§! - §G[FROM.scm_fe_firerate_variable]%§\n\n§GExtra Production from Jobs§! - §G[FROM.scm_fe_jobproduction_variable]%§\n\n§EExtra Ship Speed§! - §G[FROM.scm_fe_speed_variable]%§"\nBonus Fleets - §G[FROM.scm_fe_extrafleet_variable]§"

 scm_game_settings.2000.a:0 "Increase Ship Hull by §G10%§!"
 scm_game_settings.2000.b:0 "Decrease Ship Hull by §R10%§!"
 scm_game_settings.2000.c:0 "Increase Armor by §G10%§!"
 scm_game_settings.2000.d:0 "Decrease Armor by §R10%§!"
 scm_game_settings.2000.e:0 "Increase Shields by §G10%§!"
 scm_game_settings.2000.f:0 "Decrease Shields by §R10%§!"
 scm_game_settings.2000.g:0 "Increase Fire Rate by §G10%§!"
 scm_game_settings.2000.h:0 "Decrease Fire Rate by §R10%§!"
 scm_game_settings.2000.i:0 "Increase Job Production by §G10%§!"
 scm_game_settings.2000.j:0 "Decrease Job Production by §R10%§!"
 scm_game_settings.2000.k:0 "Increase Ship Speed by §G10%§!"
 scm_game_settings.2000.l:0 "Decrease Ship Speed by §R10%§!"
 scm_game_settings.2000.m:0 "Increase Extra Fleets by §G1§!"
 scm_game_settings.2000.n:0 "Decrease Extra Fleets by §R1§!"
 scm_game_settings.2000.z:0 "Finalize Variables, Grant Bonuses"
 scm_game_settings.2000.z1:0 "Back to Main Settings Menu"

 scm_khan_hull_variable_mod:0 "Cunningly-Savage Hulls"
 scm_khan_armor_variable_mod:0 "Cunningly-Savage Armor"
 scm_khan_shield_variable_mod:0 "Cunningly-Savage Shields"
 scm_khan_firerate_variable_mod:0 "Cunningly-Savage Gunners"
 scm_khan_jobproduction_variable_mod:0 "Cunningly-Savage Workers"
 scm_khan_speed_variable_mod:0 "Cunningly-Savage Speed"

 scm_game_settings.3000.title:0 "Force Spawn Settings"
 scm_game_settings.3000.desc:0 "Here you can choose to force spawn any or all of the crisies, trigger the Drums of War, awaken any and all Fallen Empires"
 scm_game_settings.3000.a:0 "Begin the §HPrethoryn Scourge§! event chain"
 scm_game_settings.3000.b:0 "Begin the §BUnbidden§! event chain"
 scm_game_settings.3000.c:0 "Begin the §RAI Contingency§! event chain"
 scm_game_settings.3000.d:0 "Awaken a Fallen Empire"
 scm_game_settings.3000.e:0 "Beat the Drums of War"
 scm_game_settings.3000.z:0 "Return to Main Settings Menu"
 
 scm_game_settings.4000.title:0 "One-Time Fleet Spawning Menu"
 scm_game_settings.4000.desc:0 "Here you can click-spawn an extra fleet for certain empires"
 scm_game_settings.4000.a:0 "Spawn an extra fleet for every Fallen Empire"
 scm_game_settings.4000.b:0 "Spawn an extra fleet for the Khan"
 scm_game_settings.4000.c:0 "Back to Main Settings Menu"

 scm_game_settings.5000.title:0 "Misc Settings"
 scm_game_settings.5000.desc:0 "Settings for less organized stuff"
 scm_game_settings.5000.a:0 "Force spawn the Galactic Core"
 scm_game_settings.5000.z:0 "Back to Main Settings Menu"
